#Build settings
markdown: kramdown
permalink: "blog/:title/"
paginate: 5
paginate_path: "/posts/page:num/"
baseurl: /
url: https://www.thebranch.work
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tidy
  #- jekyll-compress-images
google_analytics: UA-149944962-1
include: ['_pages']

# Site Settings
short_name: "The Branch"
language: "en"
lang_direction: "ltr"
color: "#2f2f2f"
title: "The Branch Agilidad e Innovación"
tagline: el socio en agilidad y transformación organizativa que te ayudará a descubrir una mejor forma de trabajar...
slogan: "...reinventa tu organización!"
description: The Branch es el evento de conferencias de desarrollo de software, tecnología e innovación, más grande de Panamá. Juntos evolucionamos Panamá!
community: Construyamos una comunidad de comunidades.
date: "Panamá"
place: "República de Panamá."
city: "CIUDAD DE PANAMÁ"
logo-white: '/assets/img/identity/the-branch-logo-inverted.svg' 
logo: '/assets/img/identity/the-branch-logo.svg'
favicon: 'assets/images/favicon.ico'
disqus: 'thebranch'
email: 'hola@thebranch.work'
email2: 'marvin@thebranch.work'
social-media: 
twitter: 
facebook: 
linkedin: 
instagram: 
slack: 
calendar_event: 
form_comunidades: 
form_voluntarios: 
form_speakers: 
form_patrocinadores: 
form_encuesta_comunidades: 
mailchimp-list: 
---
excerpt_separator: <!--more-->
---

imageoptim:
  pngout: false
  svgo: false
  verbose: false

#jekyll-tidy:
  #ignore_env: development